/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 14-Nov-2018 14:45:51 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Group_User]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Group] DROP CONSTRAINT [FK_Group_User]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Members_Group]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Members] DROP CONSTRAINT [FK_Members_Group]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Members_Person]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Members] DROP CONSTRAINT [FK_Members_Person]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Participants_Events]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Participants] DROP CONSTRAINT [FK_Participants_Events]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Participants_Person]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Participants] DROP CONSTRAINT [FK_Participants_Person]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Participants_Person_02]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Participants] DROP CONSTRAINT [FK_Participants_Person_02]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Events]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Events]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Group]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Group]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Members]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Members]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Participants]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Participants]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Person]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Person]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[User]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [User]
GO

/* Create Tables */

CREATE TABLE [Events]
(
	[EventID] int NOT NULL IDENTITY (1, 1),
	[EventName] varchar(50) NOT NULL
)
GO

CREATE TABLE [Group]
(
	[GroupID] int NOT NULL IDENTITY (1, 1),
	[GroupName] varchar(50) NOT NULL,
	[User_ID] int NOT NULL
)
GO

CREATE TABLE [Members]
(
	[Group_ID] int NOT NULL,
	[Person_ID] int NOT NULL,
	[MembersID] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [Participants]
(
	[Event_ID] int NOT NULL,
	[Person_ID] int NOT NULL,
	[ZielPerson_ID] int NOT NULL,
	[ParticipantsID] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [Person]
(
	[PersonID] int NOT NULL IDENTITY (1, 1),
	[FirstName] varchar(50) NOT NULL,
	[LastName] varchar(50) NOT NULL,
	[Email] varchar(50) NOT NULL
)
GO

CREATE TABLE [User]
(
	[UserID] int NOT NULL,
	[UserName] varchar(50) NOT NULL,
	[Password] varchar(50) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Events] 
 ADD CONSTRAINT [PK_Events]
	PRIMARY KEY CLUSTERED ([EventID] ASC)
GO

ALTER TABLE [Group] 
 ADD CONSTRAINT [PK_Group]
	PRIMARY KEY CLUSTERED ([GroupID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Group_Person] 
 ON [Group] ()
GO

CREATE NONCLUSTERED INDEX [IXFK_Group_Person_02] 
 ON [Group] ([User_ID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Group_User] 
 ON [Group] ([User_ID] ASC)
GO

ALTER TABLE [Members] 
 ADD CONSTRAINT [PK_Members]
	PRIMARY KEY CLUSTERED ([MembersID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Members_Group] 
 ON [Members] ([Group_ID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Members_Person] 
 ON [Members] ([Person_ID] ASC)
GO

ALTER TABLE [Participants] 
 ADD CONSTRAINT [PK_Participants]
	PRIMARY KEY CLUSTERED ([ParticipantsID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Participants_Events] 
 ON [Participants] ([Event_ID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Participants_Person] 
 ON [Participants] ([Person_ID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Participants_Person_02] 
 ON [Participants] ([ZielPerson_ID] ASC)
GO

ALTER TABLE [Person] 
 ADD CONSTRAINT [PK_Person]
	PRIMARY KEY CLUSTERED ([PersonID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Person_Person] 
 ON [Person] ()
GO

ALTER TABLE [User] 
 ADD CONSTRAINT [PK_Table1]
	PRIMARY KEY CLUSTERED ([UserID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_User_Person] 
 ON [User] ([UserID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Group] ADD CONSTRAINT [FK_Group_User]
	FOREIGN KEY ([User_ID]) REFERENCES [User] ([UserID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Members] ADD CONSTRAINT [FK_Members_Group]
	FOREIGN KEY ([Group_ID]) REFERENCES [Group] ([GroupID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Members] ADD CONSTRAINT [FK_Members_Person]
	FOREIGN KEY ([Person_ID]) REFERENCES [Person] ([PersonID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Participants] ADD CONSTRAINT [FK_Participants_Events]
	FOREIGN KEY ([Event_ID]) REFERENCES [Events] ([EventID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Participants] ADD CONSTRAINT [FK_Participants_Person]
	FOREIGN KEY ([Person_ID]) REFERENCES [Person] ([PersonID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Participants] ADD CONSTRAINT [FK_Participants_Person_02]
	FOREIGN KEY ([ZielPerson_ID]) REFERENCES [Person] ([PersonID]) ON DELETE No Action ON UPDATE No Action
GO
